### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by 360matt** [KotlinFactory/LightningStorage#32]
**Is your feature request related to a problem? Please describe.**
My data files are not synchronized on several servers, or several machines

**Describe the solution you'd like**
 I will find it more comfortable if you can add MySQL support. With the same methods (well almost), it would be really productive to be able to store data from one database and retrieve it from another server. It is a necessity for me, would you say?

**Describe alternatives you've considered**
You can add support of MySQL database as if they were files

**Additional context**
This functionality would be in my opinion one more reason to use the library

**Comment by KotlinFactory** [comment]
We created a MySQL library with the SQL module of the SimplixCore. Since it is not associated with LightningStorage it is in a [different](https://github.com/Simplix-Softworks/SimplixCore) project.
